/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData thumbs_up = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_empty = IconData(0xf0e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_alt = IconData(0xf164, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commenting = IconData(0xf27a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commenting_o = IconData(0xf27b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xf352, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_discussion = IconData(0xf3c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
